name: Test

on:
  workflow_dispatch:

jobs:
  cli-token-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli-core repo
        uses: actions/checkout@v2
      - name: Execute py script to validate twilio-cli tokens
        id: cli_token  
        run: |
          output=$(python3 .github/scripts/validate_cli_tokens.py)
          echo "::set-output name=tokenStatus::$output"
      - name: Print status
        run: echo "${{ steps.cli_token.outputs.tokenStatus }}"